spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ohgiraffers
    username: ohgiraffers
    password: ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show_sql: true
